[package]
name = "Kubera"
version = "0.0.0"

[dependencies]
#AptosFramework = { local = "./aptos-core/aptos-move/framework/aptos-framework/" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "b15d56d56283a425ccb935033d087bdd0765322d" }
MoveNursery = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/nursery/", rev = "b15d56d56283a425ccb935033d087bdd0765322d" }


[addresses]
Kubera="0x0"
AptosFramework="0x1"
Std="0x1"
#HippoSwap = "0xf70ac33c984f8b7bead655ad239d246f1c0e3ca55fe0b8bfc119aa529c4630e8"