[package]
name = "Kubera"
version = "0.0.0"

[dependencies]
#AptosFramework = { local = "./aptos-core/aptos-move/framework/aptos-framework/" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
#MoveNursery = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/nursery/", rev = "b15d56d56283a425ccb935033d087bdd0765322d" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "devnet" }


[addresses]
 kubera="0x1"
aptos_framework="0x1"
std="0x1"
dev_addr="0x01"
